# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ookami.kb's blog
email: ookami.kb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mainly Flutter and Android developer.
  Former full-stack developer, who doesn't believe that full-stack developers exist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ookami-kb.github.io"
twitter_username: ookami_kb
github_username:  ookami-kb
linkedin_username: ookamikb

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-19102123-9
disqus:
  shortname: ookami-kb

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
